### ISSUE TITLE
SOFATracer remote report data to Zipkin version 2.1.X version problem

### ISSUE THREAD

**Issue by guanchao-yang** [alipay/sofa-tracer#57]
### Describe the bug

* 1.TraceId we print to disk and report to Zipkin length are not equal.Such as print disk is  `0a0fe87a153519650379710017813` ，but in Zipkin 

![image](https://user-images.githubusercontent.com/32863418/44618633-5c3ad180-a8ac-11e8-8521-98166ee9b842.png)

* 2.SpanId and parentSpanId error. The parentSpanId in  Zipkin version 2.1.X report is blank ,

![image](https://user-images.githubusercontent.com/32863418/44618659-ca7f9400-a8ac-11e8-9ddb-55444074a60f.png)

If no parentSpanId the SOFATracer Link path will hava no layer.

### Expected behavior

TraceId should be same and  Zipkin view has the SOFATracer link path layer.

### Actual behavior

TraceId not same and parentSpanId error.

### Steps to reproduce

[Can use such example](https://github.com/guanchao-yang/sofa-tracer-demo)

**Comment by glmapper** [comment]
About the first question:The zipkin's spanId is 16 or 32 bits. If it is not satisfied, it will be padleft.as follows:
![image](https://user-images.githubusercontent.com/35319286/44764624-4adf1700-ab83-11e8-8f34-40f27ce1abb8.png)

question 2:The zipkin parentId is empty. Because in v2,v2 span model Unsets the {@link Span#parentId()} if the input is 0.So we don't need to convert hex to decimal, use FNV64HashCode to convert String to long will be OK.

And the last question,root span is not supposed to have parent AFAIK
